### ISSUE TITLE
Scratch sometimes doesn't open text files

### ISSUE THREAD

**Issue by drakofrost** [elementary/code#150]
This may be a little hard to describe, but I will try.

I have many text files in my computer, sometimes Scratch opens them, and sometimes it doesn't. When Scratch is unable to open a text file, I receive a box prompting me to choose an application to open the file, if I select Scratch, it opens the file and displays the text properly.

I can tell if this will happen before opening the file, because the icon of the text file changes to something else. As can be seen in the screenshots bellow, I have two text files, Elementary OS and To Do, the second has a different icon, and if I try to open it, I will receive the box prompting me to choose an application.

![scratch - 01](https://user-images.githubusercontent.com/24446211/27997232-74fb2f20-64ca-11e7-9954-6ac0fe5412fe.png)

![scratch - 02](https://user-images.githubusercontent.com/24446211/27997243-ad887258-64ca-11e7-8d3d-7925cfc52431.png)

This happens in both, old text files and new text files, even the ones created directly on Scratch. The weird thing is that the same file sometimes has the correct icon and opens normally, and sometimes have the other icon and doesn't open, even though I haven't edited the file.

I hope that my explanation was clear enough.

**Comment by jeremypw** [comment]
This looks it may be a FIles issue - the file type is not being determined consistently for some files.  It seems to happen if the file is edited while Files is open.  The type can change from "text file" to "unknown" and is not cured by refreshing the view.  However, if Files is closed and reopened the correct type is shown again.

I'll try and move this issue to the Files repository otherwise I'll create a new issue there and reference this one.

**Comment by drakofrost** [comment]
I believe that you are right. I have Files open pretty much all the time, I did a quick test, and it seems that closing and launching Files again works for certain files, but not all of them.

**Comment by jeremypw** [comment]
Marked as invalid as it will be fixed in Files.
