### ISSUE TITLE
Move to libide

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#401]
Ide.SourceView is a Gtk.SourceView with a lot of built-ins like overwriting braces, overscroll, etc. It might make sense to switch to that to get some features for free.

https://valadoc.org/libide-1.0/Ide.SourceView.html

**Comment by benwaffle** [comment]
@chergert how usable is libide outside of GNOME builder?

**Comment by chergert** [comment]
It's going to be difficult. libide isn't designed to be used outside of Builder. It's only really a library so that our unit tests don't take so long to re-link on every build.

In this case, bringing in IdeSourceView would necessarily bring in a host of other things like the buffer manager, diagnostics engine, search tooling, context/object, source view helpers, etc. It's a lot of code that is coupled to avoid additional moving parts.

That said, if we were going to redesign libide to be used outside of Builder (and I assume provide some level of ABI stability), we'd need to at minimum start breaking it up in a set of libraries that are smaller in scope.

**Comment by tintou** [comment]
Yeah, if we need features to the SourceView, better upstream them ourselves to GtkSource. libide has a very different scope than elementary Code, we are not providing a generic IDE at all.

**Comment by chergert** [comment]
> we are not providing a generic IDE at all

Well Builder isn't a generic IDE either. If you want to do things efficiently, you're going to end up with very similar abstractions.

This difficulty here would be:

 - agreeing on what and where those abstractions should be
 - how do plugins interact with them
 - what and where are the ABI guarantees

Some of the things will be very hard to move into GtkSourceView. For example, our gutter renderer is designed to be *very fast at rendering* because the gutter is not pixel cached in GtkTextView. That means it needs very fast access to information (ie: the data structures containing breakpoints, diagnostics, code folds, etc).

Once you gain enough features, the assemble components from GtkSourceView really falls over the edge. It's worth at least reading through the IdeSourceView code. There is a lot of slight-of-hand going on in there to keep GtkTextView/GtkSourceView fast despite the number of features we have in Builder.
