### ISSUE TITLE
Bring back text wrap setting

### ISSUE THREAD

**Issue by null-von-sushi** [elementary/code#484]
Please add an option to disable text wrap

**Comment by cassidyjames** [comment]
@null-von-sushi thanks for reporting this issue! What's the context in which you're wanting to not wrap text?

**Comment by lewisgoddard** [comment]
I assume anything where a language could reasonably have a large blob throughout a document would be much easier to navigate with this turned off. A possible example would be data64 embeds of small images that are still several wrapped lines long in HTML that otherwise has a maximum line length.

**Comment by cassidyjames** [comment]
Thanks for the feedback @null-von-sushi and @lewisgoddard! We had removed the setting a while back to see what the feedback was. In that time I've also found a few files that would be better to not be wrapped (inline base64 or something like Lewis mentioned). I would be open to re-adding it while keeping the current default. But I'd want to hear from some other folks, i.e. @elementary/ux and other developers.

**Comment by null-von-sushi** [comment]
Interesting. Default-on is fine etc., but why was this removed as an option in the first place if I may ask? I mean, if it was already implemented, wouldn't that just take away choice from the user? Just wondering.

**Comment by cassidyjames** [comment]
@null-von-sushi we frequently revisit features, especially ones that we don't use much or at all internally, especially when doing significant code and UI cleanups like we've been doing in Code over the past few months. You can find the original PR and discussion at https://github.com/elementary/code/pull/73

The nice thing is that we're always listening to user feedback and observing how we and others use our software, so nothing is permanent. I was not particularly in favor of dropping it before, and since I've run into a few places and other people now who expect it to be there, I think it's worth reconsidering.

**Comment by null-von-sushi** [comment]
Don't worry, I am not accusing the project of anything :grinning:  
I just wanted to know actual reasons of why a project might drop a feature. While I realize implementing a new features depends on whether someone is actually interested in writing the code in the first place, I never considered actually having to maintain it once it's in.

Thanks for the explaination :slightly_smiling_face:

**Comment by alvelvis** [comment]
Hi! I've been using "code" to code in Python and the indentation thing in that language makes me want to turn off wordwrap... It would be appreciated for me as well

**Comment by ezojg** [comment]
I'm using Code to view and edit tab separated files, composed by long entries. When Code breaks the lines, it messes with my view of the file. I would find a way to turn off text wrapping very useful too.
