### ISSUE TITLE
Rapidly closing files with middle mouse button re-opens some files

### ISSUE THREAD

**Issue by jlnr** [elementary/code#485]
When I have several tabs open and want to close them all, I usually hover over the first tab and click the mouse wheel repeatedly.

If I do this too fast, this accidentally triggers the feature in Code where a middle-click on the empty space in the tab bar reopens a recently closed file.

This shouldn't happen because there's always a tab under my cursor. It seems that if I double-click with the mouse wheel, the first click closes the tab as expected, and then the second click re-opens the tab, because for a split second the space under the cursor is empty.

**Comment by cassidyjames** [comment]
This may be an issue in Granite's tabs, but I can confirm the behavior in Code.

**Comment by andreasfelix** [comment]
I think the problem is that a tab can only be closed if the `close_button` is visible. But the Gtk.Revealer `close_button_revealer`, which is the parent of the `close_button`, has a transition duration of 250ms.

After closing a tab, the cursor enters a new tab and toggles the visibility of the `close_button` of this tab. As the reveal animation takes 250ms this tab cannot be closed by a middle click during this time!

Furthermore as `e.button == 2 && close_button_is_visible ()` evaluates to `false` the middle click event is not consumed by the `Tab` instead it gets handled by the `DynamicNotebook`, which leads to unwanted restoring of the last closed tab.

---
The Tab:
```vala
public Tab (string? label = null, GLib.Icon? icon = null, Gtk.Widget? page = null) {
    ...
    this.enter_notify_event.connect ((e) => {
        cursor_over_tab = true;
        update_close_button_visibility (); // <-- triggers 250ms animation
        return false;
    });
    ...
    this.button_press_event.connect ((e) => {
        if (e.button == 2 && close_button_is_visible ()) { // <-- The close button of the next tab is not visible when clicking fast enough
            e.state &= MODIFIER_MASK;

            if  (e.state == 0) {
                this.closed ();
            } else if (e.state == Gdk.ModifierType.SHIFT_MASK) {
                this.close_others ();
            }
        } else if {
          ...
        } else {
            return false; // <-- button_press_event is handelt by Dynamic notebook, which restores last closed tab!
        }
return true;
```
DynamicNotebook:
```vala
button_press_event.connect ((e) => {
    if (e.type == Gdk.EventType.2BUTTON_PRESS && e.button == 1) {
        new_tab_requested ();
    } else if (e.button == 2 && allow_restoring) {
        restore_last_tab (); // <-- Middle click opens new tab
        return true;
    } else if (e.button == 3) {
        menu.popup_at_pointer (e);
    }

    return false;
});
```

Check transition duration:
```vala
debug("%u", close_button_revealer.get_transition_duration());`
```

**Comment by jlnr** [comment]
Fixed here https://github.com/elementary/granite/issues/294
