### ISSUE TITLE
Use inline toolbar style on tab bar

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#493]
Since elementary/stylesheet#379 was merged. This will require:

- [ ] Defining `@define-color tab_base_color $FOO` in application CSS where `$FOO` is the background color of the current syntax scheme. 
- [ ] Changing that variable when the style scheme changes. We _could_ try to introspect into the style scheme to get that color, _or_ we could just define three versions based on the style scheme switcher, since we know what scheme we're going to use there. Just depends on how complex we want to get.
- [ ] Adding the `.inline-toolbar` style class to the Dynamic Notebook widget.

**Comment by davidmhewitt** [comment]
Introspecting the style scheme isn't too hard, I already have code to do that in #434 

I'll try and submit a PR for this soon.

**Comment by cassidyjames** [comment]
![screenshot from 2018-08-15 09 54 44 2x](https://user-images.githubusercontent.com/611168/44158222-70432f80-a071-11e8-8e1f-741fb9bfc029.png)

![screenshot from 2018-08-15 09 55 29 2x](https://user-images.githubusercontent.com/611168/44158221-6faa9900-a071-11e8-9cd5-232e1b9053d0.png)

![screenshot from 2018-08-15 09 55 51 2x](https://user-images.githubusercontent.com/611168/44158220-6faa9900-a071-11e8-939f-02c501c8e4fd.png)

**Comment by lux-walsh** [comment]
I don't know if this deserves a separate issue, but there is some UI inconsistency with the new style of tab-bar. Since users can scroll in non-whole line increments, it is possible to have a line of text get halfway cut off by the tab bar. In the old style, this is not a problem, since there is a weighted line that traces the cutoff point, suggesting that the tab bar is being drawn _over_ the text view. In the new style however, there is no such line _under the active tab_, and so it looks like a rendering error: The text is  simultaneously presented as being on the same level as the active tab and below it. 
![Screenshot from 2019-05-25 10-23-00](https://user-images.githubusercontent.com/51027967/58372184-32641900-7ed7-11e9-81e3-a0205a3d7d1b.png)
