### ISSUE TITLE
Different (old?) icons used in code vs terminal

### ISSUE THREAD

**Issue by japetrus** [elementary/code#535]
It appears to me, at least when running the live session from the Juno installer, that the icons and spacing for the find and settings buttons are different. This seems to not be in line with elementary's elegant design philosophy. Screenshots attached.
![code](https://user-images.githubusercontent.com/5879432/47086189-d3268380-d1e6-11e8-88e2-dc61d028d053.png)
![terminal](https://user-images.githubusercontent.com/5879432/47086190-d3268380-d1e6-11e8-9de4-44f8bef683b2.png)

**Comment by cassidyjames** [comment]
@japetrus this is because they use different types of window controls. Terminal has a small titlebar with inline icons—these are drawn in a "symbolic" style where they're just one color. Code, on the other hand, uses a full header bar with full-color icons. This is because we pack more widgets into the header bar and it's a much larger part of the UI. It would be inconsistent with all of our other header bar apps if we used symbolic icons in Code instead of full-color icons.

I do see a contrast issue with the search icon in Code, but that would be an issue for the icons repo.
