### ISSUE TITLE
Terminal extention open in current directory.

### ISSUE THREAD

**Issue by micahilbery** [elementary/code#58]
I think it makes sense for the terminal extension to open the terminal in the current working directory. If not by default than with an option or a extra click.

**Comment by jeremypw** [comment]
@micahilbery What do you mean by current directory ()?  Is this the directory returned by GLib.Environment.get_current_dir (or the PWD environment variable) or the directory that the current document is in?  Or the directory selected in the folder manager sidebar? Or the root directory in the folder manager sidebar?

**Comment by micahilbery** [comment]
@jeremypw I would say probably the directory selected in the folder manager sidebar. But I could also see a case for the directory the current document is in. It just seems odd that when working on a project and then opening the terminal extension pane it has no relation to currently opened project/document. Currently it doesn't feel like there is much benefit to using the terminal extension over just opening the terminal app and tiling it.

**Comment by jeremypw** [comment]
OK, thanks.  I am not sure whether different plugins can communicate with each other at the moment so that is probably the hardest option - although I agree it is probably the best option.  I have pushed some commits to the linked PR that implement following the current document path - I'll look into the other option.
