### ISSUE TITLE
Change repo to "code"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#61]
Will need to coordinate with automatic builds and translations, plus probably give people a heads up that it moved.

**Comment by Garbee** [comment]
May I ask why rename the program to simply `code`? If the binary is eventually moved to this then it could conflict with Microsoft's [Visual Studio Code](https://code.visualstudio.com/) which uses `code` as the binary name. Which means in order to install and use VS Code you then must give up this program.

It seems like an odd choice to chose this for a rename when a major company in the development sphere is already using the name. While I understand it aligns with the naming conventions Elementary is looking for, perhaps alternatives should be investigated before jumping further in with this rename.

**Comment by danrabbit** [comment]
There will be a blog post soon. The binary name will not conflict as we use RDNN naming scheme (`io.elementary.code`)

**Comment by danrabbit** [comment]
Closing since this is done
