### ISSUE TITLE
Expand/collapse all projects in sidebar

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#656]
I think this would make sense to live in an inline toolbar (#554) in the sidebar. If you're working with a bunch of projects, it would be handy to be able to collapse them all down at once to help you start organized.

**Comment by roymckenzie** [comment]
@cassidyjames my PR #657 might resolve this issue. "Collapse Project Folders" is an option in the `GtkMenu ()` triggered by clicking on a new Menu button in the right side of the inline toolbar from PR #569.

I thought about adding an "Expand Project Folders" option to the menu as well. I decided not to because I couldn't think of a use case where I wanted all project folders expanded.

Keeping it off the menu (even though it could provide some utility, would allow users to access the much more likely used functionality ("Collapse Project Folders") more quickly. 

We could do "Toggle Project Folders," but that hides/masks the useful obviousness of  "Collapse Project Folders."

I have opinions!

Any thoughts?

**Comment by cassidyjames** [comment]
@roymckenzie yeah I'm not opposed to just starting with collapse. Expanding seems less immediately useful.
