### ISSUE TITLE
Help info is not displayed correctly in terminal

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#666]
Related to #488 but happens in English environment and formatting is worse.

![Screenshot from 2019-04-15 19 15 15](https://user-images.githubusercontent.com/10513844/56155476-e3ab9100-5fb2-11e9-90d5-2f702dac4760.png)

**Comment by ryonakano** [comment]
@jeremypw I'm sorry, but the title of #488 which I made was not accurate. I wanted to mean that this issue happens if we're running our system in any localized languages, but I completely forgot that there are some localized Englishes like en_GB, en_AU, en_CA, and so on. So I think this issue is duplicate of #488.

**Comment by jeremypw** [comment]
OK, I guess I forgot that English English is a localization!
