### ISSUE TITLE
Duplicated file loses Syntax Highlighting

### ISSUE THREAD

**Issue by kedicesur** [elementary/code#817]
Duplicating a file either by

1. Right clicking on it's tab and selecting `Duplicate` or

2. Just by double clicking on it's tab

creates a new file called `New Document` and the Syntax Highlighting resets to `Plain Text`. People mostly duplicate files as a matchstick version control system so most possibly they intend making some changes by keeping the previous code.

I believe it should keep all the state regarding that file including the extension hence Syntax Highlighting. For instance when `myFile.hs` is duplicated, the duplicate can be renamed like `myFile (copy).hs` at least in one of the above duplication choices. This would also be inline with what Files do when a file is copied pasted into the same directory.

**Comment by jeremypw** [comment]
@kedicesur  At the moment, a duplicated document is created "unsaved" - which is why the tab is labelled "New Document". Is this the desired behaviour or would you expect the duplicate file to created in the folder of the original document?  The problem with this is, the user is likely to want to save it under a different name/path than "File (copy)" which would then result in an unwanted file.  

So, it is not easy to arrange that the tab is labelled "File (copy)" at the same time as keeping the document as "unsaved"  (i.e. saved in a temporary location).
