### ISSUE TITLE
Add contextual menu to open file in new view view

### ISSUE THREAD

**Issue by febrezo** [elementary/code#859]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

Add a new contextual menu to the file explorer to open the file in a new view.

**Describe the solution you'd like**

It would be helpful to add a new contextual menu to open a file in a new view instead of only allowing to open in a new window. 

**Existing work**

Currently, the only way I found to do so is to manually go to `Settings`, create a new view and the clicking on the file.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A

**Comment by cassidyjames** [comment]
We've actually deprecated the slit views in Code, as it seems to duplicate a lot of the work going into window tiling and lead to several focus issues. In future versions of elementary OS, we plan to remove the split view completely. You can hide the sidebar (Ctrl+Backslash or F9) to get more usable space in each window, and then tiling side-by-side lets the window manager handle tiling instead of re-implementing it inside of Code.

**Comment by febrezo** [comment]
That's not a bad solution. I'm experiencing some wrong behaviours in splitted views like clicking in a different file in the left (main) pane, affecting the viewable file in both views, which was not my expected result. I will adapt my workflow to split the views side by side in new windows. Just missing an OS shortcut to adjust them to top-left, top-right, bottom-left, bottom-right (Ctrl + Num 9, Ctrl + Num 7, etc.) but that's just another issue. Thanks for the response.
